# -----------------------------------------------------------------
# token ${token}
# -----------------------------------------------------------------
[token.${token}.asset_type]
module = "pdo.exchange.plugins.asset_type"
identity = "token_type"
source = "${ContractFamily.Exchange.asset_type.source}"
name = "${token}"
description = "asset type for ${token} token objects"
link = "http://"

[token.${token}.vetting]
module = "pdo.exchange.plugins.vetting"
identity = "token_vetting"
source = "${ContractFamily.Exchange.vetting.source}"
asset_type_context = "@{..asset_type}"

[token.${token}.guardian]
module = "pdo.exchange.plugins.guardian"
identity = "${..token_issuer.identity}"
source = "${ContractFamily.Exchange.data_guardian.source}"
token_issuer_context = "@{..token_issuer}"

[token.${token}.token_issuer]
module = "pdo.exchange.plugins.token_issuer"
identity = "token_issuer"
source = "${ContractFamily.Exchange.token_issuer.source}"
token_object_context = "@{..token_object}"
vetting_context = "@{..vetting}"
guardian_context = "@{..guardian}"
description = "issuer for token ${token}"
count = 10

[token.${token}.token_issuer.token_metadata]
opaque = "this is opaque"

[token.${token}.token_object]
module = "pdo.exchange.plugins.token_object"
identity = "${..token_issuer.identity}"
source = "${ContractFamily.Exchange.token_object.source}"
token_issuer_context = "@{..token_issuer}"
data_guardian_context = "@{..guardian}"
